---
name: Test

on:
  # push:
  #  branches: ["master"]
  # pull_request:
  #  branches: ["master"]
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: "18.x"

      - name: Install newman
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - uses: actions/checkout@v4

      - name: Create Env File
        run: |
          cp exemple.env .env

      - name: Docker Compose Action
        uses: isbang/compose-action@v2.0.2

      - name: Run Newman
        run: |
          newman run "./postman/collections/Minetest Skin Server_30e29402-3ae4-4cad-ba2e-150af06d3912.json" -r htmlextra --reporter-htmlextra-export ./postman/report.html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: ./postman/report.html
